### ISSUE TITLE
Introduction to the Hooked World of React - Abril 2019

### ISSUE THREAD

**Issue by sergiodxa** [limaFrontend/organizacion#10]
**¿Qué tipo de propuesta deseas realizar?**

- [x] Charla (compartir un tema)
- [ ] Workshop (Taller)
- [ ] Aviso de trabajo / Anuncio / Promocion / Etc.
- [ ] Bootcamp
- [ ] Hackaton
- [ ] Otro (Especificar aquí)

**¿En que categoría de tecnologia se encuentra tu propuesta?**

- [x] Javascript 
- [ ] CSS 
- [ ] Android 
- [ ] iOS 
- [ ] UX
- [ ] Prototipado / UI
- [ ] Otro (Especificar aquí)

**¿Cuanto será la duración de tu propuesta?**

- [ ] Aviso rápido (Algunos minutos)
- [ ] 15 mins (Algo breve)
- [x] 30 / 45 mins  (Charla promedio)
- [ ] 1 Hora (Evento extendido)
- [ ] ¿Necesitas más tiempo? (poner tiempo aquí)

**¿Cuál es el titulo de tu propuesta de evento o charla?**
_Introduction to the Hooked World of React_

**Describe de que se trata tu propuesta**
Una introducción a React Hooks comparando ejemplos con clases.

**¿Algún requerimiento técnico o de tu equipo?**

- [ ] Cable HDMI
- [ ] Cable VGA
- [x] Adaptador para MAC
- [ ] Otro (Especifica aquí)

**¿Vienes por tu cuenta o representas a alguna organización o empresa?**
1. [Able](https://able.co) - Agencia de desarrollo web (soy empleado)
2. [Tech Talks](https://techtalks.pe) - Meetup de tecnología (soy organizador)

**Dejamos tus nombres y una breve descripción de ti y lo que haces**
Trabajo como Senior Software Engineer en Able. Lidero Tech Talks Perú. Soy contribuidor de varias librerías OSS en JavaScript, incluyendo Next.js, micro, serve, Now CLI, etc. Dicté cursos y talleres de React, Redux y Now en Platzi. Soy autor del libro "Desarrollo de Aplicaciones Web con React.js y Redux.js". 

**Déjanos un enlace de tu red social favorita o tu e-mail para que sea fácil contactarte**
https://twitter.com/sergiodxa

**Comment by techfano** [comment]
Muchas gracias Sergio! Queda agenda-da tu charla para el viernes 29 de Marzo. Cualquier consulta no dudes en contactarnos por interno.

**Comment by techfano** [comment]
Hola @sergiodxa Muchas Gracias por tu propuesta!! Te quería consultar si podemos mover tu charla para el próximo mes (Abril). Debido a que este mes vamos a hacer un meetup solo de speakers mujeres.

**Comment by sergiodxa** [comment]
Hola, si claro no hay problema!

**Comment by techfano** [comment]
Genial @sergiodxa programo tu charla para el meetup de abril entonces 😃
