### ISSUE TITLE
Gestionando Paquetes: Dependencias Confiables - Abril 2019

### ISSUE THREAD

**Issue by faurehu** [limaFrontend/organizacion#11]
_Marque las opciones con una "x" ejemplo: - [x] opción_

**¿Qué tipo de propuesta deseas realizar?**
Charla

**¿En que categoría de tecnologia se encuentra tu propuesta?**

- [x] Javascript 
- [ ] CSS 
- [ ] Android 
- [ ] iOS 
- [ ] UX
- [ ] Prototipado / UI
- [x] Otro (Especificar aquí)

**¿Cuanto será la duración de tu propuesta?**

30 mins

**¿Cuál es el titulo de tu propuesta de evento o charla?**

Gestionando Paquetes: Dependencias Confiables

**Describe de que se trata tu propuesta**

Una amigable introducción al manejo de dependencias. Queremos entender bien de que consiste todas esas lineas que tenemos en nuestros proyectos pero que no hemos escrito nosotros mismos. Tambien queremos protegernos contra problemas concretos que suceden en nuestros proyectos y muchas veces se deben a nuestro gestor de paquetes. 

**¿Algún requerimiento técnico o de tu equipo?**

- [ ] Cable HDMI
- [ ] Cable VGA
- [x] Adaptador para MAC
- [ ] Otro (Especifica aquí)

**¿Vienes por tu cuenta o representas a alguna organización o empresa?**

Soy programador freelancer pero doy charlas para dar a conocer el canal de youtube que acabo de lanzar:
https://www.youtube.com/channel/UCt17skdI3JngDj0kHZGyypA

**Dejamos tus nombres y una breve descripción de ti y lo que haces**

Soy un ingeniero de sistemas que lleva 10 años en el extranjero. He trabajado para empresas como Finimize y Deliveroo (Glovo europeo). Actualmente trabajo con un stack de Typescript, React y Yoga.

**Déjanos un enlace de tu red social favorita o tu e-mail para que sea fácil contactarte**
[@hu_am__i](twitter.com/hu_am__i)
[hi@faure.hu](emailto:hi@faure.hu)

**Comment by techfano** [comment]
Hola @faurehu Muchas Gracias por tu propuesta!! Te quería consultar si podemos mover tu charla para el próximo mes (Abril). Debido a que mes vamos a hacer un meetup solo de speakers mujeres.

**Comment by faurehu** [comment]
@techfano ningún problema, me confirman :thumbs_up:

**Comment by techfano** [comment]
Si Claro @faurehu, muchas gracias por tu comprensión, tu charla queda agenda-da para el viernes 26 de Abril
