### ISSUE TITLE
[UX research: ¿Que tipo de investigación y en que etapa realizarlo?] - [Abril 2019]

### ISSUE THREAD

**Issue by franshescaqm** [limaFrontend/organizacion#13]
_Marque las opciones con una "x" ejemplo: - [x] opción_

**¿Qué tipo de propuesta deseas realizar?**

- [x] Charla (compartir un tema)
- [ ] Workshop (Taller)
- [ ] Aviso de trabajo / Anuncio / Promocion / Etc.
- [ ] Bootcamp
- [ ] Hackaton
- [ ] Otro (Especificar aquí)

**¿En que categoría de tecnologia se encuentra tu propuesta?**

- [ ] Javascript 
- [x] CSS 
- [ ] Android 
- [ ] iOS 
- [x] UX
- [x] Prototipado / UI
- [ ] Otro (Especificar aquí)

**¿Cuanto será la duración de tu propuesta?**

- [x] Aviso rápido (Algunos minutos)
- [ ] 15 mins (Algo breve)
- [ ] 30 / 45 mins  (Charla promedio)
- [ ] 1 Hora (Evento extendido)
- [ ] ¿Necesitas más tiempo? (poner tiempo aquí)

**¿Cuál es el titulo de tu propuesta de evento o charla?**
Intenta ser breve y conciso con el titulo (No más 70 letras es recomendable)

**Describe de que se trata tu propuesta**
(Un Máximo de 30 palabras es recomendable)

**¿Algún requerimiento técnico o de tu equipo?**

- [ ] Cable HDMI
- [ ] Cable VGA
- [ ] Adaptador para MAC
- [ ] Otro (Especifica aquí)

**¿Vienes por tu cuenta o representas a alguna organización o empresa?**
Por mi propia cuenta.

**Dejamos tus nombres y una breve descripción de ti y lo que haces**
Soy una ux designer que ha empezado a trabajr en este rubro hace pocos meses y todavía hay mucho
por aprender y super ansiosa de conocer la experiencia de otras personas obteniendo más conocimiento. 

**Déjanos un enlace de tu red social favorita o tu e-mail para que sea fácil contactarte**
https://www.linkedin.com/in/franshesca-quezada/
Correo: Franshesca_94@hotmail.com

**Comment by franshescaqm** [comment]
Soy una UX que ha empezado recientemente en este rubro y para conocer y obtener más conocimientos sobre mi entorno de trabajo ire al evento individualmente. Mi red social más usada es linkedin: https://www.linkedin.com/in/franshesca-quezada/

**Comment by techfano** [comment]
Hola @franshescaqm! Muchas gracias por tu propuesta, ahora nos comunicamos pronto contigo para coordinar.

Saludos
