### ISSUE TITLE
Microservice performance testing - Mayo 2019

### ISSUE THREAD

**Issue by ldiego73** [limaFrontend/organizacion#14]
_Marque las opciones con una "x" ejemplo: - [x] opción_

**¿Qué tipo de propuesta deseas realizar?**

- [x] Charla (compartir un tema)
- [ ] Workshop (Taller)
- [ ] Aviso de trabajo / Anuncio / Promocion / Etc.
- [ ] Bootcamp
- [ ] Hackaton
- [ ] Otro (Especificar aquí)

**¿En que categoría de tecnologia se encuentra tu propuesta?**

- [x] Javascript 
- [ ] CSS 
- [ ] Android 
- [ ] iOS 
- [ ] UX
- [ ] Prototipado / UI
- [ ] Otro (Especificar aquí)

**¿Cuanto será la duración de tu propuesta?**

- [ ] Aviso rápido (Algunos minutos)
- [ ] 15 mins (Algo breve)
- [] 30 / 45 mins  (Charla promedio)
- [x] 1 Hora (Evento extendido)
- [ ] ¿Necesitas más tiempo? (poner tiempo aquí)

**¿Cuál es el titulo de tu propuesta de evento o charla?**
Microservice performance testing

**Describe de que se trata tu propuesta**
La importancia de poder realizar pruebas de performance de los microservicios que vayamos a utilizar dentro de nuestras aplicaciones y como estos pueden afectar en ellas, con la finalidad de prevenir que nuestras aplicaciones que estamos desarrollando sean escalables.

**¿Algún requerimiento técnico o de tu equipo?**

- [x] Cable HDMI
- [ ] Cable VGA
- [x] Adaptador para MAC
- [ ] Otro (Especifica aquí)

**¿Vienes por tu cuenta o representas a alguna organización o empresa?**
Belcorp

**Dejamos tus nombres y una breve descripción de ti y lo que haces**
Soy Luis Diego, Arquitecto de Soluciones con más de 11 años desarrollando y 3 años como rol de arquitecto.

**Déjanos un enlace de tu red social favorita o tu e-mail para que sea fácil contactarte**
https://www.facebook.com/ldiego73
https://www.instagram.com/ldiego73
https://www.linkedin.com/in/ldiego73

**Comment by techfano** [comment]
Hola @ldiego73!! Muchas Gracias por tu propuesta! Estamos coordinando pronto para agendar el horario y algunos detalles.
