### ISSUE TITLE
[Sitios web estáticos con Gatsby y Strapi] - [Julio2019]

### ISSUE THREAD

**Issue by rsurjano** [limaFrontend/organizacion#16]
_Marque las opciones con una "x" ejemplo: - [x] opción_

**¿Qué tipo de propuesta deseas realizar?**

- [x] Charla (compartir un tema)
- [ ] Workshop (Taller)
- [ ] Aviso de trabajo / Anuncio / Promocion / Etc.
- [ ] Bootcamp
- [ ] Hackaton
- [ ] Otro (Especificar aquí)

**¿En que categoría de tecnologia se encuentra tu propuesta?**

- [x ] Javascript 
- [ ] CSS 
- [ ] Android 
- [ ] iOS 
- [ ] UX
- [ ] Prototipado / UI
- [ ] Otro (Especificar aquí)

**¿Cuanto será la duración de tu propuesta?**

- [ ] Aviso rápido (Algunos minutos)
- [ ] 15 mins (Algo breve)
- [x ] 30 / 45 mins  (Charla promedio)
- [ ] 1 Hora (Evento extendido)
- [ ] ¿Necesitas más tiempo? (poner tiempo aquí)

**¿Cuál es el titulo de tu propuesta de evento o charla?**
Sitios web estáticos con Gatsby y Strapi

**Describe de que se trata tu propuesta**
Existe un auge enorme este año por la generación de sitios web estáticos, es muy recomendable que difundamos este paradigma y analizar como nos beneficia y como podríamos adoptarlo.

**¿Algún requerimiento técnico o de tu equipo?**

- [x] Cable HDMI
- [x] Cable VGA
- [ ] Adaptador para MAC
- [ ] Otro (Especifica aquí)

**¿Vienes por tu cuenta o representas a alguna organización o empresa?**
Arnat Technologies https://www.arnat.digital

**Dejamos tus nombres y una breve descripción de ti y lo que haces**
Soy Roy Surjano, tengo mas de 8 años en el desarrollo de software y actualmente dirijo una empresa de software de reciente creación: Arnat Technologies

**Déjanos un enlace de tu red social favorita o tu e-mail para que sea fácil contactarte**
https://facebook.com/rsurjano
https://www.linkedin.com/in/rsurjano/
https://twitter.com/rsurjano

**Comment by larissaswisher** [comment]
good
