### ISSUE TITLE
[Microfrontends: equipos multifuncionales y autónomos evolucionando productos] - [Octubre 2019]

### ISSUE THREAD

**Issue by luchoalarcon** [limaFrontend/organizacion#21]
_Marque las opciones con una "x" ejemplo: - [x] opción_

**¿Qué tipo de propuesta deseas realizar?**

- [X] Charla (compartir un tema)
- [ ] Workshop (Taller)
- [ ] Aviso de trabajo / Anuncio / Promocion / Etc.
- [ ] Bootcamp
- [ ] Hackaton
- [ ] Otro (Especificar aquí)

**¿En que categoría de tecnologia se encuentra tu propuesta?**

- [X] Javascript 
- [X] CSS 
- [ ] Android 
- [ ] iOS 
- [X] UX
- [X] Prototipado / UI
- [ ] Otro (Especificar aquí)

**¿Cuanto será la duración de tu propuesta?**

- [ ] Aviso rápido (Algunos minutos)
- [ ] 15 mins (Algo breve)
- [X] 30 / 45 mins  (Charla promedio)
- [ ] 1 Hora (Evento extendido)
- [ ] ¿Necesitas más tiempo? (poner tiempo aquí)

**¿Cuál es el titulo de tu propuesta de evento o charla?**
Microfrontends: equipos multifuncionales y autónomos evolucionando productos.  

**Describe de que se trata tu propuesta**
Microfrontends desde la trinchera: Qué son y cómo nos vienen ayudando en la creación y evolución de productos, manteniendo una misma experiencia de usuario.

**¿Algún requerimiento técnico o de tu equipo?**

- [X] Cable HDMI
- [ ] Cable VGA
- [X] Adaptador para MAC
- [ ] Otro (Especifica aquí)

**¿Vienes por tu cuenta o representas a alguna organización o empresa?**
Por nuestra cuenta.

**Dejamos tus nombres y una breve descripción de ti y lo que haces**
Somos 2 apasionados del software, practicantes Agile Software Development, XP, DevOps, Clean Code & en continuo aprendizaje.

**Déjanos un enlace de tu red social favorita o tu e-mail para que sea fácil contactarte**
- https://www.linkedin.com/in/luisoalarconc
- https://www.linkedin.com/in/psalguerodev/

**Comment by techfano** [comment]
Hola @lucho-alarcon !  Te queria consuktar si podiamos mover tu charla para Noviembre. Debido a que tenemos full la agenda este mes.

Saludos.

**Comment by luchoalarcon** [comment]
Hola ,
Listo, no hay problemas.
Saludos.
