### ISSUE TITLE
Testing en el Mundo del Frontend - Noviembre 2019

### ISSUE THREAD

**Issue by sergiodxa** [limaFrontend/organizacion#22]
**¿Qué tipo de propuesta deseas realizar?**

- [x] Charla (compartir un tema)
- [ ] Workshop (Taller)
- [ ] Aviso de trabajo / Anuncio / Promocion / Etc.
- [ ] Bootcamp
- [ ] Hackaton
- [ ] Otro (Especificar aquí)

**¿En que categoría de tecnologia se encuentra tu propuesta?**

- [x] Javascript 
- [ ] CSS 
- [ ] Android 
- [ ] iOS 
- [ ] UX
- [ ] Prototipado / UI
- [ ] Otro (Especificar aquí)

**¿Cuanto será la duración de tu propuesta?**

- [ ] Aviso rápido (Algunos minutos)
- [ ] 15 mins (Algo breve)
- [x] 30 / 45 mins  (Charla promedio)
- [ ] 1 Hora (Evento extendido)
- [ ] ¿Necesitas más tiempo? (poner tiempo aquí)

**¿Cuál es el titulo de tu propuesta de evento o charla?**

Testing en el Mundo del Frontend

**Describe de que se trata tu propuesta**

Repaso por las diferentes formas y técnicas para hacer testings y darnos seguridad de que nuestra aplicación Frontend va a funcionar, empezando por linters, pasando por tippado, unit tests, snapshots, test de integración y terminando con end-to-end. Todo viendo ejemplo con código.

**¿Algún requerimiento técnico o de tu equipo?**

- [ ] Cable HDMI
- [ ] Cable VGA
- [x] Adaptador para MAC
- [ ] Otro (Especifica aquí)

**¿Vienes por tu cuenta o representas a alguna organización o empresa?**

1. [Able](https://able.co) - Agencia de desarrollo web
2. [Tech Talks](https://techtalks.pe) - Meetup de tecnología

**Dejamos tus nombres y una breve descripción de ti y lo que haces** 

Sergio Xalambrí aprendió programación de forma autodidacta y trabaja como Tech Lead en Able. Lidera Tech Talks Perú. Es contribuidor de varias librerías de código abierto en JavaScript, incluyendo Next.js, micro, serve, Now CLI y más. Dictó cursos online y talleres presenciales de React, Redux y ZEIT Now en Colombia como parte del equipo de Platzi. Es también autor del libro "Desarrollo de Aplicaciones Web con React.js y Redux.js".

**Déjanos un enlace de tu red social favorita o tu e-mail para que sea fácil contactarte**

https://twitter.com/sergiodxa

**Comment by techfano** [comment]
Hola @sergiodxa ! Excelente, queda agenda-da tu charla para noviembre.

Saludos!
