### ISSUE TITLE
[GoKarma UX + BKN + Front] - [Octubre 2019]

### ISSUE THREAD

**Issue by Themvp07** [limaFrontend/organizacion#23]
_Marque las opciones con una "x" ejemplo: - [x] opción_

**¿Qué tipo de propuesta deseas realizar?**

- [x] Charla (compartir un tema)
- [ ] Workshop (Taller)
- [ ] Aviso de trabajo / Anuncio / Promocion / Etc.
- [ ] Bootcamp
- [ ] Hackaton
- [ ] Otro (Especificar aquí)

**¿En que categoría de tecnologia se encuentra tu propuesta?**

- [ ] Javascript 
- [ ] CSS 
- [ ] Android 
- [ ] iOS 
- [x] UX
- [ ] Prototipado / UI
- [ ] Otro (Especificar aquí)

**¿Cuanto será la duración de tu propuesta?**

- [ ] Aviso rápido (Algunos minutos)
- [ ] 15 mins (Algo breve)
- [x] 30 / 45 mins  (Charla promedio)
- [ ] 1 Hora (Evento extendido)
- [ ] ¿Necesitas más tiempo? (poner tiempo aquí)

**¿Cuál es el titulo de tu propuesta de evento o charla?**
Equipo SatoshiElQueLoLea representante de competición intercontinental

**Describe de que se trata tu propuesta**
Luego de ganar la Hackathon representaremos al país en la final continental y nos gustaría presentar el proyecto para recibir feedback por parte de la comunidad tecnológica
**¿Algún requerimiento técnico o de tu equipo?**

- [ ] Cable HDMI
- [x] Cable VGA
- [ ] Adaptador para MAC
- [ ] Otro (Especifica aquí)

**¿Vienes por tu cuenta o representas a alguna organización o empresa?**
Equipo: SatoshiElQueLoLea - Ganador Hackathon Blockchain Series Edición Lima

**Dejamos tus nombres y una breve descripción de ti y lo que haces**
Fares Akel - Profesional en tecnología de blockchain aplicada, entrenador de equipos universitarios internacionales para competir en Modelos de Naciones Unidas.
Percy Meneses - Desarrollador Front-end, apasionado por el aprendizaje eterno.
Simón León - Ingeniero, filántropo, podcaster, tecno evangelista.

**Déjanos un enlace de tu red social favorita o tu e-mail para que sea fácil contactarte**
Twitter - @fares_akel - @percymeneses08 - @simoxpe

**Comment by techfano** [comment]
Hola @Themvp07  podríamos mover tu charla para noviembre? Tenemos la agenda a full este mes. Saludos

**Comment by Themvp07** [comment]
no hay problema Estefano, si se puede a principios de noviembre sería genial. Agradecido

**Comment by techfano** [comment]
@Themvp07 Hola! Ya esta confirmada tu charla para este Miércoles 20 de Noviembre

Saludos
