### ISSUE TITLE
[Inserte titulo aquí] - [indique un mes de ser necesario ejem: Diciembre 2019]

### ISSUE THREAD

**Issue by yesusmen** [limaFrontend/organizacion#25]
_Marque las opciones con una "x" ejemplo: - [x] opción_

**¿Qué tipo de propuesta deseas realizar?**

- [ ] Charla (compartir un tema)
- [x ] Workshop (Taller)
- [ ] Aviso de trabajo / Anuncio / Promocion / Etc.
- [ ] Bootcamp
- [ ] Hackaton
- [ ] Otro (Especificar aquí)

**¿En que categoría de tecnologia se encuentra tu propuesta?**

- [x ] Javascript 
- [x ] CSS 
- [x ] Android 
- [ ] iOS 
- [x ] UX
- [x ] Prototipado / UI
- [x ] Otro (Xamarin, Flutter)

**¿Cuanto será la duración de tu propuesta?**

- [ ] Aviso rápido (Algunos minutos)
- [ ] 15 mins (Algo breve)
- [x ] 30 / 45 mins  (Charla promedio)
- [ ] 1 Hora (Evento extendido)
- [ ] ¿Necesitas más tiempo? (poner tiempo aquí)

**¿Cuál es el titulo de tu propuesta de evento o charla?**
Intenta ser breve y conciso con el titulo (No más 70 letras es recomendable)

**Describe de que se trata tu propuesta**
(Un Máximo de 30 palabras es recomendable)

**¿Algún requerimiento técnico o de tu equipo?**

- [ ] Cable HDMI
- [ ] Cable VGA
- [ ] Adaptador para MAC
- [ ] Otro (Especifica aquí)

**¿Vienes por tu cuenta o representas a alguna organización o empresa?**
En caso pertenezcas a alguna organización, déjanos aquí el nombre, enlace y una breve descripción de la misma.

**Dejamos tus nombres y una breve descripción de ti y lo que haces**
Describe aquí una pequeña biografía sobre ti. (40 palabras es lo recomendable)

**Déjanos un enlace de tu red social favorita o tu e-mail para que sea fácil contactarte**
(twitter/facebook/linkedin/e-mail)

**Comment by techfano** [comment]
Hola @yesusmen 

Que tema deseas proponer para tu charla?
Quedo atento a tu respuesta.

Saludos
