### ISSUE TITLE
Animación Web con CSS y Javascript Vanilla

### ISSUE THREAD

**Issue by pleonm** [limaFrontend/organizacion#4]
**Cual es el titulo de tu charla o tema que deseas aprender**
Intenta ser breve y conciso con el titulo (no más 70 letras es recomendable)

Animación Web con CSS y Javascript Vanilla

**Describe de que se trata tu propuesta**
(Un Maximo de 30 palabras es recomendable)

Sería una charla de 45min aproximadamente tipo workshop donde se verá el desarrollo de animaciones HTML5 desde el análisis del diseño, exportación de los elementos, generación de los estados de animación con CSS y control del guion usando Javascript. 

**Algun requerimiento técnico o de tu equipo**

- [X] Cable HDMI
- [ ] Cable VGA
- [ ] Adaptador para MAC 

Puede ser conexión mediante AirPlay si lo tuvieran.

**Vienes por tu cuenta o representas a alguna organización o empresa**
En caso pertenezcas a alguna organización, déjanos aquí el nombre, enlace y una breve descripción de la misma.

Voy por mi cuenta pero tengo un estudio digital: Innova Digital Studio 
http://innovadigitalstudio.com/

**Dejamos aquí una breve descripción de ti y lo que haces**
Describe aquí una pequeña biografia sobre ti. (40 palabras es lo recomendable)

Mi nombre es Pedro León Mindreau, de profesión Ingeniero industrial y programador con más de 20 años de experiencia en la planificación, diseño y desarrollo de proyectos web y multimedia. Docente desde hace 24 años en técnicas y herramientas informáticas para el diseño y desarrollo web y multimedia en diferentes instituciones como Toulouse Lautrec, New Horizons, Escuela de arte digital, BPRO Design Training Center, entre otros.

Entre los principales proyectos de desarrollo web se encuentran la creación de sitios web corporativos, sitios para campañas publicitarias, sitios de ecommerce, desarrollo de campañas de banners digitales para marcas reconocidas como Toyota, Honda, Nestea, IKEA, AT&T, T-Mobile, Mitsubishi, Wells Fargo, Chase Bank, Scion, Swat, Applebee's, Kiehl's, entre otras. 

Me pueden contactar a los siguientes emails:
pedroleon72@gmail.com
pedro@innovadigitalstudio.com

**Comment by techfano** [comment]
Hola Pedro! Muchas gracias por tu propuesta, la he revisado y queda genial para este 28 de febrero, así que queda agendada para este mes. Cualquier duda que tengas no dudes en comunicarte con nosotros por aquí, por email o cualquier medio disponible.

**Comment by pleonm** [comment]
Muy bien, así quedamos, vamos coordinando antes de la fecha, cualquier cosa me escribes.
