### ISSUE TITLE
UX 101: Necesito hacer 'UX' y no sé cómo

### ISSUE THREAD

**Issue by pixiepixeled** [limaFrontend/organizacion#5]
UX 101: Necesito hacer 'UX' y no sé cómo

## Descripción de tu charla
Cuando en un equipo no se cuenta con UX Designer le toca al dev asumir ese rol, en la charla descubriremos prácticas y herramientas usadas en UX que todo dev debe conocer.

## Estructura de tu charla
* UX y UX Design
* ¿Por qué un dev debe conocer de UX?
* Prácticas y herramientas

## Algun requerimiento técnico o de tu equipo
-  Cable HDMI

## Tus datos personales (nombre, bio, url y foto)
**Andrea Maucaylli**
UX Designer, voluntaria en WiT Perú y staff de Más mujeres en UX Perú.

* https://www.linkedin.com/in/andrea-maucaylli/ (Bio, Foto)

**Comment by techfano** [comment]
Genial Andrea! Gracias por compartir y ayudarnos a difundir conocimiento. Cualquier cosa no dudes en contactarte con nosotros por interno. Queda agenda-da tu charla para este 28 de febrero.
