### ISSUE TITLE
PROGRAMADORES VS DISEÑADORES (Como trabajar en equipo sin morir en el intento)

### ISSUE THREAD

**Issue by fredichin** [limaFrontend/organizacion#6]
**Cual es el título de tu charla o tema que deseas aprender**
PROGRAMADORES VS DISEÑADORES (Como trabajar en equipo sin morir en el intento)

**Describe de qué se trata tu propuesta**
Diferencias entre ambos perfiles y consejos para mejorar el flujo de trabajo durante un proyecto

**Algún requerimiento técnico o de tu equipo**
- [ ] Cable HDMI
- [ ] Parlantes

**Vienes por tu cuenta o representas a alguna organización o empresa**
Por mi cuenta

**Dejamos aquí una breve descripción de ti y lo que haces**
Talentoso y creativo UX Designer especializado Diseño Web e Interfaces de Usuario con más de 8 años de experiencia en la elaboración de productos digitales y conocimientos en Diseño Web/Móvil, Gráfico, Multimedia, Institucional, Analítica Web, SEO, Maquetación, Marketing Digital y Redes sociales.

**Comment by techfano** [comment]
Muchas gracias Fredy! Queda agenda-da tu charla para este 28 de febrero. Cualquier cosa no dudes contactarte con nosotros por interno.
